name: "security_scan"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  call-security-scan-from-org-repo:
    uses: JLLT-Apps/security-workflows/.github/workflows/security_scan.yml@stable
    with:
      APPID: ${{ vars.APPID }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
