name: "snyk_import"
on:
  workflow_dispatch:
    inputs:
      GET_SNYK_ORG_ONLY:
        type: string
        description: "Flag to indicate whether to get Snyk org only or not"
        required: false
        default: 'false'

jobs:
  call_snyk_import:
    uses: JLLT-Apps/security-workflows/.github/workflows/snyk_import.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      FINE_CHECKOUT_PAT: ${{ secrets.FINE_CHECKOUT_PAT }}
    with:
      REPO_LONG_NAME: ${{ github.repository }}
