#################################################################################
### THIS SECTION IS MANAGED BY THE REPOSITORY VENDING MACHINE - DO NOT CHANGE ###
#################################################################################

name: "SCA Build Action"
description: "Install all required dependencies"
runs-on: ubuntu-latest
runs:
  using: "composite"

#################################################################################
### THIS SECTION IS MANAGED BY THE REPOSITORY VENDING MACHINE - DO NOT CHANGE ###
#################################################################################
#### YOUR BUILD PROCESS NEEDS TO BE BELOW LINE 15 AND WILL START WITH steps: ####
#################################################################################
  steps:
    - name: Do Nothing
      shell: bash
      run: echo "Setup your build process in sca-build/action.yml"

### Examples ###

# Java/Node
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#      - name: run MVN install
#        run: mvn install # install maven

#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'

# Python
#  steps:
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.9'

#    - name: Install dependencies
#      shell: bash
#      run: |
#        pip install -r requirements.txt

# Go
#    steps:
#      - uses: actions/checkout@master
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - name: Build
#        run: go build -v ./...
#      - name: Tidy
#        run: go mod tidy
